name: Build ubox

on:
  push:
  pull_request:

jobs:
  build-backports:
    name: Build ubox
    runs-on: ubuntu-latest

    container:
      image: alpine:latest

    steps:
      - name: Install Dependencies
        run: |
          apk update && apk add git cmake make gcc musl-dev pkgconfig json-c-dev linux-headers lua5.1 lua5.1-dev

      - name: Install libubox
        run: |
          git clone	--depth=1 https://git.openwrt.org/project/libubox.git

          cd libubox
          cmake -DBUILD_EXAMPLES=OFF
          make
          make install

      - name: Install libubus
        run: |
          git clone	--depth=1 https://git.openwrt.org/project/ubus.git

          cd ubus
          cmake -DBUILD_EXAMPLES=OFF
          make
          make install

      - name: Install libuci
        run: |
          git clone	--depth=1 https://git.openwrt.org/project/uci.git

          cd uci
          cmake .
          make
          make install

      - name: Install libudebug
        run: |
          git clone	--depth=1 https://github.com/jow-/ucode

          cd ucode
          cmake .
          make
          make install

      - name: Install libudebug
        run: |
          git clone	--depth=1 https://git.openwrt.org/project/udebug.git

          cd udebug
          cmake .
          make
          make install

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install ubox
        run: |
          cmake .
          make
          make install
